export { default as HomePage } from './HomePage'
export { default as CheckOutPage } from './CheckOutPage'
export { default as AboutUsPage } from './AboutUsPage'
export { default as ShopPage } from './ShopPage'
export { default as LoginPage } from './auth/LoginPage'